import React, { useState, useEffect, useRef, useMemo } from 'react';
import Prism from 'prismjs';
import 'prismjs/components/prism-javascript';
import { ROW_COLORS, SOUNDS } from '../utils/patterns.js';
import '../styles/code-view.css';

/**
 * CodeView — Alive code display with beat-synced animations
 *
 * Renders the composed Strudel code with:
 * - Per-line colored left borders matching sequencer row colors
 * - Bounce animation when a line's row triggers on beat
 * - Pattern character parsing: x = bright/bold, ~ = dim/faded
 * - Moving cursor highlighting the current step position within patterns
 * - Prism syntax highlighting for non-pattern code parts
 *
 * SAFETY NOTE on innerHTML / dangerouslySetInnerHTML usage:
 * The `code` prop is exclusively generated by composeLayerCode() in layers.js —
 * it is never user-supplied HTML. Prism.highlight() output contains only
 * <span class="token ..."> wrappers for syntax tokens. renderPatternLine()
 * produces only controlled span elements with class names and inline styles.
 * This is a safe, controlled use of dangerouslySetInnerHTML for syntax coloring,
 * identical in safety profile to the original CodeView implementation.
 * No user input ever reaches innerHTML. All content is internally generated.
 *
 * @param {Object} props
 * @param {string} props.code - Full Strudel code string from composed layers
 * @param {Function} props.onCodeClick - Callback when user clicks in the code area
 * @param {number|null} props.flashLine - Line index to flash (0-indexed), or null
 * @param {*} props.flashKey - Changes when flash should re-trigger
 * @param {number|null} props.beatStep - Current beat step (0-indexed), or null when not playing
 * @param {number} props.stepCount - Number of active steps (8 or 16)
 */
function CodeView({ code, onCodeClick, flashLine = null, flashKey, beatStep = null, stepCount = 8 }) {
  const [copied, setCopied] = useState(false);
  const [activeFlashLine, setActiveFlashLine] = useState(null);
  const flashTimerRef = useRef(null);
  const prevBeatStepRef = useRef(null);

  // --- Flash effect: highlight the changed line briefly ---
  useEffect(() => {
    if (flashLine == null) return;

    if (flashTimerRef.current) {
      clearTimeout(flashTimerRef.current);
    }

    setActiveFlashLine(flashLine);

    flashTimerRef.current = setTimeout(() => {
      setActiveFlashLine(null);
      flashTimerRef.current = null;
    }, 600);

    return () => {
      if (flashTimerRef.current) {
        clearTimeout(flashTimerRef.current);
      }
    };
  }, [flashLine, flashKey]);

  // --- Copy to clipboard ---
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      const textarea = document.createElement('textarea');
      textarea.value = code;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    }
  };

  // --- Parse code into display lines ---
  // Splits stack() into individual sound lines for per-row rendering
  const parsedLines = useMemo(() => {
    if (!code) return [];

    // Match stack(...) wrapping — extract individual statements
    const stackMatch = code.match(/^stack\(([\s\S]+)\)$/);
    if (stackMatch) {
      const inner = stackMatch[1];
      // Split on commas that separate top-level s("...") statements
      // Handle both single-line and multi-line stack() formats
      const statements = [];
      let depth = 0;
      let current = '';

      for (let i = 0; i < inner.length; i++) {
        const ch = inner[i];
        if (ch === '(') depth++;
        else if (ch === ')') depth--;
        else if (ch === ',' && depth === 0) {
          statements.push(current.trim());
          current = '';
          continue;
        }
        current += ch;
      }
      if (current.trim()) statements.push(current.trim());

      // Build lines: "stack(" + individual statements + ")"
      const lines = [];
      lines.push({ type: 'wrapper', text: 'stack(' });
      statements.forEach((stmt, idx) => {
        lines.push({
          type: 'sound',
          text: stmt,
          soundIndex: findSoundIndex(stmt),
          isLast: idx === statements.length - 1,
        });
      });
      lines.push({ type: 'wrapper', text: ')' });
      return lines;
    }

    // Single statement (no stack wrapper) — could be a single sound line
    const structMatch = code.match(/\.struct\(/);
    if (structMatch) {
      return [{
        type: 'sound',
        text: code,
        soundIndex: findSoundIndex(code),
        isLast: true,
      }];
    }

    // Fallback: split by newlines, use Prism for everything
    return code.split('\n').map(line => ({
      type: 'other',
      text: line,
    }));
  }, [code]);

  // Track beat step changes for bounce trigger
  useEffect(() => {
    prevBeatStepRef.current = beatStep;
  }, [beatStep]);

  // --- Render Functions ---

  /**
   * Render a sound line with pattern character parsing.
   * Splits the .struct("x ~ x ~") portion into individually styled characters.
   *
   * SAFETY: All HTML is generated from controlled sources — Prism.highlight()
   * on internally-generated code strings, and pattern chars are single characters
   * ('x' or '~') extracted from composeLayerCode() output. No user input involved.
   */
  function renderSoundLine(line, lineIndex) {
    const { text, soundIndex, isLast } = line;
    const color = soundIndex >= 0 && soundIndex < ROW_COLORS.length
      ? ROW_COLORS[soundIndex]
      : '#5c6370';

    // Parse the struct pattern out of the statement
    const structRegex = /^(.*\.struct\(")([^"]+)("\).*)$/;
    const match = text.match(structRegex);

    if (!match) {
      // No struct pattern found — use Prism highlighting
      const suffix = isLast ? '' : ',';
      // SAFETY: Prism.highlight() only produces span.token wrappers on internal code
      const highlighted = Prism.highlight(
        text + suffix,
        Prism.languages.javascript,
        'javascript'
      );
      return renderHighlightedLine(highlighted, lineIndex, color, soundIndex);
    }

    const prefix = match[1];   // e.g. s("RolandTR808_bd").struct("
    const pattern = match[2];  // e.g. x ~ x ~ x x ~ x
    const suffix = match[3];   // e.g. ")
    const comma = isLast ? '' : ',';

    // Parse pattern characters (split on spaces)
    const chars = pattern.split(' ');

    // Determine if this line should bounce:
    // Bounce when the current beatStep hits an 'x' in this row
    const shouldBounce = beatStep !== null
      && soundIndex >= 0
      && beatStep < chars.length
      && chars[beatStep] === 'x';

    // Build the prefix HTML via Prism
    // SAFETY: prefix is from composeLayerCode() — internally generated code string
    const prefixHtml = Prism.highlight(prefix, Prism.languages.javascript, 'javascript');
    // Build the suffix HTML via Prism
    // SAFETY: suffix is from composeLayerCode() — internally generated code string
    const suffixHtml = Prism.highlight(suffix + comma, Prism.languages.javascript, 'javascript');

    // Build pattern characters HTML — each char is 'x' or '~', never user input
    const patternHtml = chars.map((ch, ci) => {
      const isCursor = beatStep !== null && ci === beatStep;
      const isHit = ch === 'x';
      const isRest = ch === '~';

      let classes = 'pattern-char';
      if (isHit) classes += ' pattern-hit';
      if (isRest) classes += ' pattern-rest';
      if (isCursor) classes += ' pattern-cursor';
      if (isCursor && isHit) classes += ' pattern-cursor-hit';

      // Space before char (except first)
      const space = ci > 0 ? '<span class="pattern-space"> </span>' : '';

      const style = isCursor && isHit
        ? ` style="--char-color: ${color}"`
        : '';

      return `${space}<span class="${classes}"${style}>${ch}</span>`;
    }).join('');

    const fullHtml = `${prefixHtml}${patternHtml}${suffixHtml}`;

    const lineClasses = [
      'code-line',
      'code-line-sound',
      activeFlashLine === lineIndex ? 'flash' : '',
      shouldBounce ? 'code-line-bounce' : '',
    ].filter(Boolean).join(' ');

    return (
      <div
        key={lineIndex}
        className={lineClasses}
        style={{ borderLeftColor: color }}
        // SAFETY: fullHtml is composed from Prism.highlight() output (safe span.token
        // wrappers) and controlled pattern char spans. No user input reaches innerHTML.
        dangerouslySetInnerHTML={{ __html: fullHtml || '\u00a0' }}
      />
    );
  }

  /**
   * Render a line using full Prism highlighting (for wrapper lines or non-pattern code).
   * SAFETY: html param is always from Prism.highlight() on internally-generated code.
   */
  function renderHighlightedLine(html, lineIndex, borderColor, soundIndex) {
    const lineClasses = [
      'code-line',
      soundIndex >= 0 ? 'code-line-sound' : '',
      activeFlashLine === lineIndex ? 'flash' : '',
    ].filter(Boolean).join(' ');

    const style = soundIndex >= 0 ? { borderLeftColor: borderColor } : {};

    return (
      <div
        key={lineIndex}
        className={lineClasses}
        style={style}
        dangerouslySetInnerHTML={{ __html: html || '\u00a0' }}
      />
    );
  }

  /**
   * Render a wrapper line (stack open/close parens) with Prism highlighting.
   * SAFETY: line.text is 'stack(' or ')' — hardcoded wrapper strings.
   */
  function renderWrapperLine(line, lineIndex) {
    const highlighted = Prism.highlight(
      line.text,
      Prism.languages.javascript,
      'javascript'
    );

    return (
      <div
        key={lineIndex}
        className={`code-line code-line-wrapper${activeFlashLine === lineIndex ? ' flash' : ''}`}
        dangerouslySetInnerHTML={{ __html: highlighted || '\u00a0' }}
      />
    );
  }

  /**
   * Render a generic code line with Prism highlighting.
   * SAFETY: line.text is from composeLayerCode() — internally generated.
   */
  function renderOtherLine(line, lineIndex) {
    const highlighted = Prism.highlight(
      line.text,
      Prism.languages.javascript,
      'javascript'
    );

    return (
      <div
        key={lineIndex}
        className={`code-line${activeFlashLine === lineIndex ? ' flash' : ''}`}
        dangerouslySetInnerHTML={{ __html: highlighted || '\u00a0' }}
      />
    );
  }

  return (
    <div className="code-view" onClick={onCodeClick}>
      {/* Header bar */}
      <div className="code-view-header">
        <span className="code-view-title">Strudel Code</span>
        <button
          className="code-view-copy"
          onClick={(e) => {
            e.stopPropagation();
            handleCopy();
          }}
          aria-label="Copy code to clipboard"
          disabled={!code}
        >
          {copied ? 'Copied!' : 'Copy'}
        </button>
      </div>

      {/* Code display — per-line rendering with alive animations */}
      <pre className="code-view-pre">
        <code>
          {parsedLines.length > 0 ? (
            parsedLines.map((line, i) => {
              switch (line.type) {
                case 'sound':
                  return renderSoundLine(line, i);
                case 'wrapper':
                  return renderWrapperLine(line, i);
                case 'other':
                default:
                  return renderOtherLine(line, i);
              }
            })
          ) : (
            <div className="code-line code-line-empty">
              <span className="token comment">{'// tap some cells to make music'}</span>
            </div>
          )}
        </code>
      </pre>
    </div>
  );
}

/**
 * Find the SOUNDS array index for a code statement by matching sample name.
 * Returns -1 if no match found.
 */
function findSoundIndex(statement) {
  for (let i = 0; i < SOUNDS.length; i++) {
    if (statement.includes(SOUNDS[i].sample)) {
      return i;
    }
  }
  return -1;
}

export default CodeView;
