import React, { useState, useEffect, useRef } from 'react';
import Prism from 'prismjs';
import 'prismjs/components/prism-javascript';
import '../styles/code-view.css';

/**
 * CodeView — Live syntax-highlighted code display panel
 *
 * Renders the composed Strudel code with Prism.js One Dark-style
 * token coloring. Dark terminal aesthetic, monospace font, per-line
 * rendering for flash animation support.
 *
 * Uses Prism's string-based API (Prism.highlight) rather than
 * DOM-based highlightElement — avoids flicker, works with React.
 *
 * @param {Object} props
 * @param {string} props.code - Full Strudel code string from composed layers
 * @param {Function} props.onCodeClick - Callback when user clicks in the code area
 * @param {number|null} props.flashLine - Line index to flash (0-indexed), or null
 * @param {*} props.flashKey - Changes when flash should re-trigger (e.g., Date.now())
 */
function CodeView({ code, onCodeClick, flashLine = null, flashKey }) {
  const [copied, setCopied] = useState(false);
  const [activeFlashLine, setActiveFlashLine] = useState(null);
  const flashTimerRef = useRef(null);

  // --- Flash effect: highlight the changed line briefly ---
  useEffect(() => {
    if (flashLine == null) return;

    // Clear any existing flash timer
    if (flashTimerRef.current) {
      clearTimeout(flashTimerRef.current);
    }

    setActiveFlashLine(flashLine);

    flashTimerRef.current = setTimeout(() => {
      setActiveFlashLine(null);
      flashTimerRef.current = null;
    }, 600);

    return () => {
      if (flashTimerRef.current) {
        clearTimeout(flashTimerRef.current);
      }
    };
  }, [flashLine, flashKey]);

  // --- Copy to clipboard ---
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // Fallback for older browsers / insecure contexts
      const textarea = document.createElement('textarea');
      textarea.value = code;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    }
  };

  // --- Syntax highlighting via Prism string API ---
  //
  // SAFETY NOTE: The `code` prop is exclusively generated by composeLayerCode()
  // in layers.js — it is never user-supplied HTML. Prism.highlight() output
  // contains only <span class="token ..."> wrappers for syntax tokens.
  // This is a safe, controlled use of innerHTML for syntax coloring.
  //
  const highlighted = code
    ? Prism.highlight(code, Prism.languages.javascript, 'javascript')
    : '';

  // Split into per-line HTML strings for individual line rendering
  const lines = highlighted ? highlighted.split('\n') : [];

  return (
    <div className="code-view" onClick={onCodeClick}>
      {/* Header bar */}
      <div className="code-view-header">
        <span className="code-view-title">Strudel Code</span>
        <button
          className="code-view-copy"
          onClick={(e) => {
            e.stopPropagation(); // Don't trigger onCodeClick
            handleCopy();
          }}
          aria-label="Copy code to clipboard"
          disabled={!code}
        >
          {copied ? 'Copied!' : 'Copy'}
        </button>
      </div>

      {/* Code display — per-line rendering for flash animation support */}
      <pre className="code-view-pre">
        <code>
          {lines.length > 0 ? (
            lines.map((lineHtml, i) => (
              <div
                key={i}
                className={`code-line${activeFlashLine === i ? ' flash' : ''}`}
                dangerouslySetInnerHTML={{ __html: lineHtml || '\u00a0' }}
              />
            ))
          ) : (
            <div className="code-line code-line-empty">
              {/* Empty state — no layers active */}
              <span className="token comment">{'// tap some cells to make music'}</span>
            </div>
          )}
        </code>
      </pre>
    </div>
  );
}

export default CodeView;
